### PR TITLE
Level consistency fix

### PR DESCRIPTION
**Pull request by Petar121**
LEVEL_THRESHOLD wasn't consistent with the thresholds present on class sheets, since on the sheets level 1 is 0 exp. 
image
For example, Hugin is saying I'm level 3 with 8 exp here instead of level 4.
Adding 0 to LEVEL_THRESHOLD should fix this issue.

### CODE REVIEW

**Comment by Petar121** [comment]
Since making this request I've looked over the code more and have realized this change would most likely mess up other instances of LEVEL_THRESHOLD being used in the code. There is still an inconsistency between the intended level and exp values and the ones that are in the bot, but it has to be fixed in another way.

**Comment by franluque2** [comment]
Perhaps just editing the text in the data view and just adding a +1?

**Comment by Petar121** [comment]
That would solve specifically the issue of that panel being inaccurate, but there are also some other issues that need to be fixed. The pool buckets in kdr_data.py have their level requirements as one less than what they should be because levels are counted from 0 instead of from 1, for example. I'll take a more detailed look when I have the time.

**Comment by Petar121** [comment]
The status panel should now be consistent with pool unlock requirements. I've decided to not change anything else because it's an question of taste whether level 1 should be 0 exp or 2 exp, and the code works as is.

**Pull request merged**
